# Name of your application. Used to uniquely configure containers.
service: daily_health

# Name of the container image.
image: adriano-tsurumaki/daily-health

# Deploy to these servers.
servers:
  web:
    - 143.244.148.197
  # job:
  #   hosts:
  #     - 143.244.148.197
  #   cmd: bin/jobs
  #   options:
  #     health-cmd: bin/jobs-healthy

# Requer config.assume_ssl e config.force_ssl em production.rb.
proxy:
  host: <%= ENV.fetch("APP_DOMAIN") %>
  app_port: 3000
  ssl: true
  forward_headers: true
  healthcheck:
    path: /up
    interval: 5
    timeout: 10

# GitHub Container Registry.
registry:
  server: ghcr.io
  username: adriano-tsurumaki
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - APP_DOMAIN
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - RESEND_API_KEY
    - RESEND_FROM_EMAIL
  clear:
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: enabled
    POSTGRES_HOST: daily_health-db
    POSTGRES_DATABASE: daily_health_prod
    POSTGRES_USERNAME: daily_health_prod
    POSTGRES_PORT: 5432

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - 'daily_health_storage:/app/storage'

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /app/public/assets

# SSH configuration for deploy (requires 'deploy' user with docker group on server).
ssh:
  user: deploy

# Configure the image builder.
builder:
  arch: amd64
  dockerfile: docker/Dockerfile

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  db:
    image: postgres:16-alpine
    host: 143.244.148.197
    # TODO: Verify if it's necessary to expose port for access
    # port: '127.0.0.1:5432:5432'
    env:
      clear:
        POSTGRES_DB: daily_health_prod
        POSTGRES_USER: daily_health_prod
      secret:
        - POSTGRES_PASSWORD
    directories:
      - postgres_data:/var/lib/postgresql/data
